version: "3.8"

services:
  webblog:
    build: .
    container_name: webblog
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./blog.db:/app/blog.db
    environment:
      - NODE_ENV: production
      - PORT: 3001
    restart: unless-stopped
